CREATE TABLE public.master_store_list (
    stop_id TEXT PRIMARY KEY,
    store TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    stop_id_2 TEXT,
    start TIME,
    lunch_start TIME,
    lunch_end TIME,
    "end" TIME,
    saturday_hours_and_notes TEXT,
    action_flag BOOLEAN,
    banner TEXT,
    stop_id_3 TEXT,
    region TEXT,
    do_not_sell_list BOOLEAN,
    sold_here BOOLEAN,
    full_stop BOOLEAN,
    direct BOOLEAN,
    sprint BOOLEAN,
    supply TEXT,
    cin7_name TEXT,
    last_visit DATE,
    on_gs BOOLEAN,
    on_fss BOOLEAN,
    address_full TEXT,
    ship_eligible BOOLEAN
);
