CREATE TABLE public.master_visit_log (
    stop_id TEXT,
    store TEXT,
    date DATE,
    stop_type TEXT,
    service_rep TEXT,
    invoice_number INTEGER,
    blank TEXT,
    inv_adj TEXT,
    stop_completed_manual BOOLEAN,
    stop_completed BOOLEAN,
    urgency TEXT,
    optimo_status TEXT,
    direct_order BOOLEAN,
    direct_invoice_number INTEGER,
    direct_delivered BOOLEAN,
    order_parked BOOLEAN,
    rsr_optimoroute_notes TEXT,
    direct_order_dollar_amount_match BOOLEAN,
    direct_order_quantity_match BOOLEAN,
    full_service_invoice_number INTEGER,
    full_service_dollar_amount_match BOOLEAN,
    out_of_stock_count INTEGER,
    po_number_direct INTEGER,
    po_number_full_service INTEGER,
    notes TEXT,
    must_have_formula BOOLEAN,
    unique_id TEXT PRIMARY KEY,
    unique_id_doshit TEXT,
    unique_id_target TEXT,
    edi TEXT,
    region TEXT
);

