CREATE TABLE public.master_store_list (
    stop_id TEXT PRIMARY KEY,
    store TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    start_time TIME,
    lunch_start TIME,
    lunch_end TIME,
    end_time TIME,
    saturday_hours_and_notes TEXT,
    action_flag TEXT,
    store_abbr TEXT,
    banner TEXT,
    region TEXT,
    do_not_sell_list TEXT,
    sold_here TEXT,
    full_stop SMALLINT,
    direct SMALLINT,
    sprint SMALLINT,
    supply SMALLINT,
    cin7_name TEXT,
    last_visit DATE,
    on_gs BOOLEAN,
    on_fss BOOLEAN,
    address_full TEXT,
    ship_eligible BOOLEAN
);

